# Generated by Django 2.2.6 on 2019-12-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profesor',
            table='profesor2',
        ),
    ]
