# Generated by Django 2.2.6 on 2019-12-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_auto_20191218_1625'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profesor',
            table='profesor',
        ),
    ]
